DROP TABLE IF EXISTS `product_attribute`;

CREATE TABLE `product_attribute` (
  `id` int NOT NULL AUTO_INCREMENT,
  `product_item_id` int NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `product_attribute_ibfk_1` (`product_item_id`),
  CONSTRAINT `product_attribute_ibfk_1` FOREIGN KEY (`product_item_id`) REFERENCES `product_item` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=766 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `product_attribute` (`id`, `product_item_id`, `value`)
VALUES (1,1,'Neural Engine 16 lõi'),
       (2,1,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (3,1,'Camera FaceTime HD 1080p'),
       (4,1,'Cổng sạc MagSafe 3'),
       (5,1,'Hai cổng Thunderbolt / USB 4'),
       (6,1,'Hỗ trợ một màn hình ngoài'),
       (7,1,'Magic Keyboard với Touch ID'),
       (8,1,'Bàn di chuột Force Touch'),
       (9,1,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (10,2,'Neural Engine 16 lõi'),
       (11,2,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (12,2,'Camera FaceTime HD 1080p'),
       (13,2,'Cổng sạc MagSafe 3'),
       (14,2,'Hai cổng Thunderbolt / USB 4'),
       (15,2,'Hỗ trợ một màn hình ngoài'),
       (16,2,'Magic Keyboard với Touch ID'),
       (17,2,'Bàn di chuột Force Touch'),
       (18,2,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (19,3,'Neural Engine 16 lõi'),
       (20,3,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (21,3,'Camera FaceTime HD 1080p'),
       (22,3,'Cổng sạc MagSafe 3'),
       (23,3,'Hai cổng Thunderbolt / USB 4'),
       (24,3,'Hỗ trợ một màn hình ngoài'),
       (25,3,'Magic Keyboard với Touch ID'),
       (26,3,'Bàn di chuột Force Touch'),
       (27,3,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (28,4,'Neural Engine 16 lõi'),
       (29,4,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (30,4,'Camera FaceTime HD 1080p'),
       (31,4,'Cổng sạc MagSafe 3'),
       (32,4,'Hai cổng Thunderbolt / USB 4'),
       (33,4,'Hỗ trợ một màn hình ngoài'),
       (34,4,'Magic Keyboard với Touch ID'),
       (35,4,'Bàn di chuột Force Touch'),
       (36,4,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (37,5,'Neural Engine 16 lõi'),
       (38,5,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (39,5,'Camera FaceTime HD 1080p'),
       (40,5,'Cổng sạc MagSafe 3'),
       (41,5,'Hai cổng Thunderbolt / USB 4'),
       (42,5,'Hỗ trợ một màn hình ngoài'),
       (43,5,'Magic Keyboard với Touch ID'),
       (44,5,'Bàn di chuột Force Touch'),
       (45,5,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (46,6,'Neural Engine 16 lõi'),
       (47,6,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (48,6,'Camera FaceTime HD 1080p'),
       (49,6,'Cổng sạc MagSafe 3'),
       (50,6,'Hai cổng Thunderbolt / USB 4'),
       (51,6,'Hỗ trợ một màn hình ngoài'),
       (52,6,'Magic Keyboard với Touch ID'),
       (53,6,'Bàn di chuột Force Touch'),
       (54,6,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (55,7,'Neural Engine 16 lõi'),
       (56,7,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (57,7,'Camera FaceTime HD 1080p'),
       (58,7,'Cổng sạc MagSafe 3'),
       (59,7,'Hai cổng Thunderbolt / USB 4'),
       (60,7,'Hỗ trợ một màn hình ngoài'),
       (61,7,'Magic Keyboard với Touch ID'),
       (62,7,'Bàn di chuột Force Touch'),
       (63,7,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (64,8,'Neural Engine 16 lõi'),
       (65,8,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (66,8,'Camera FaceTime HD 1080p'),
       (67,8,'Cổng sạc MagSafe 3'),
       (68,8,'Hai cổng Thunderbolt / USB 4'),
       (69,8,'Hỗ trợ một màn hình ngoài'),
       (70,8,'Magic Keyboard với Touch ID'),
       (71,8,'Bàn di chuột Force Touch'),
       (72,8,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (73,9,'Neural Engine 16 lõi'),
       (74,9,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (75,9,'Camera FaceTime HD 1080p'),
       (76,9,'Cổng sạc MagSafe 3'),
       (77,9,'Hai cổng Thunderbolt / USB 4'),
       (78,9,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (79,9,'Magic Keyboard với Touch ID'),
       (80,9,'Bàn di chuột Force Touch'),
       (81,9,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (82,10,'Neural Engine 16 lõi'),
       (83,10,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (84,10,'Camera FaceTime HD 1080p'),
       (85,10,'Cổng sạc MagSafe 3'),
       (86,10,'Hai cổng Thunderbolt / USB 4'),
       (87,10,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (88,10,'Magic Keyboard với Touch ID'),
       (89,10,'Bàn di chuột Force Touch'),
       (90,10,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (91,11,'Neural Engine 16 lõi'),
       (92,11,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (93,11,'Camera FaceTime HD 1080p'),
       (94,11,'Cổng sạc MagSafe 3'),
       (95,11,'Hai cổng Thunderbolt / USB 4'),
       (96,11,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (97,11,'Magic Keyboard với Touch ID'),
       (98,11,'Bàn di chuột Force Touch'),
       (99,11,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (100,12,'Neural Engine 16 lõi'),
       (101,12,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (102,12,'Camera FaceTime HD 1080p'),
       (103,12,'Cổng sạc MagSafe 3'),
       (104,12,'Hai cổng Thunderbolt / USB 4'),
       (105,12,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (106,12,'Magic Keyboard với Touch ID'),
       (107,12,'Bàn di chuột Force Touch'),
       (108,12,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (109,13,'Neural Engine 16 lõi'),
       (110,13,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (111,13,'Camera FaceTime HD 1080p'),
       (112,13,'Cổng sạc MagSafe 3'),
       (113,13,'Hai cổng Thunderbolt / USB 4'),
       (114,13,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (115,13,'Magic Keyboard với Touch ID'),
       (116,13,'Bàn di chuột Force Touch'),
       (117,13,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (118,14,'Neural Engine 16 lõi'),
       (119,14,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (120,14,'Camera FaceTime HD 1080p'),
       (121,14,'Cổng sạc MagSafe 3'),
       (122,14,'Hai cổng Thunderbolt / USB 4'),
       (123,14,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (124,14,'Magic Keyboard với Touch ID'),
       (125,14,'Bàn di chuột Force Touch'),
       (126,14,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (127,15,'Neural Engine 16 lõi'),
       (128,15,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (129,15,'Camera FaceTime HD 1080p'),
       (130,15,'Cổng sạc MagSafe 3'),
       (131,15,'Hai cổng Thunderbolt / USB 4'),
       (132,15,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (133,15,'Magic Keyboard với Touch ID'),
       (134,15,'Bàn di chuột Force Touch'),
       (135,15,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (136,16,'Neural Engine 16 lõi'),
       (137,16,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (138,16,'Camera FaceTime HD 1080p'),
       (139,16,'Cổng sạc MagSafe 3'),
       (140,16,'Hai cổng Thunderbolt / USB 4'),
       (141,16,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (142,16,'Magic Keyboard với Touch ID'),
       (143,16,'Bàn di chuột Force Touch'),
       (144,16,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (145,17,'Neural Engine 16 lõi'),
       (146,17,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (147,17,'Camera FaceTime HD 1080p'),
       (148,17,'Cổng sạc MagSafe 3'),
       (149,17,'Hai cổng Thunderbolt / USB 4'),
       (150,17,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (151,17,'Magic Keyboard với Touch ID'),
       (152,17,'Bàn di chuột Force Touch'),
       (153,17,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (154,18,'Neural Engine 16 lõi'),
       (155,18,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (156,18,'Camera FaceTime HD 1080p'),
       (157,18,'Cổng sạc MagSafe 3'),
       (158,18,'Hai cổng Thunderbolt / USB 4'),
       (159,18,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (160,18,'Magic Keyboard với Touch ID'),
       (161,18,'Bàn di chuột Force Touch'),
       (162,18,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (163,19,'Neural Engine 16 lõi'),
       (164,19,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (165,19,'Camera FaceTime HD 1080p'),
       (166,19,'Cổng sạc MagSafe 3'),
       (167,19,'Hai cổng Thunderbolt / USB 4'),
       (168,19,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (169,19,'Magic Keyboard với Touch ID'),
       (170,19,'Bàn di chuột Force Touch'),
       (171,19,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (172,20,'Neural Engine 16 lõi'),
       (173,20,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (174,20,'Camera FaceTime HD 1080p'),
       (175,20,'Cổng sạc MagSafe 3'),
       (176,20,'Hai cổng Thunderbolt / USB 4'),
       (177,20,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (178,20,'Magic Keyboard với Touch ID'),
       (179,20,'Bàn di chuột Force Touch'),
       (180,20,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (181,21,'Neural Engine 16 lõi'),
       (182,21,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (183,21,'Camera FaceTime HD 1080p'),
       (184,21,'Cổng sạc MagSafe 3'),
       (185,21,'Hai cổng Thunderbolt / USB 4'),
       (186,21,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (187,21,'Magic Keyboard với Touch ID'),
       (188,21,'Bàn di chuột Force Touch'),
       (189,21,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (190,22,'Neural Engine 16 lõi'),
       (191,22,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (192,22,'Camera FaceTime HD 1080p'),
       (193,22,'Cổng sạc MagSafe 3'),
       (194,22,'Hai cổng Thunderbolt / USB 4'),
       (195,22,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (196,22,'Magic Keyboard với Touch ID'),
       (197,22,'Bàn di chuột Force Touch'),
       (198,22,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (199,23,'Neural Engine 16 lõi'),
       (200,23,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (201,23,'Camera FaceTime HD 1080p'),
       (202,23,'Cổng sạc MagSafe 3'),
       (203,23,'Hai cổng Thunderbolt / USB 4'),
       (204,23,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (205,23,'Magic Keyboard với Touch ID'),
       (206,23,'Bàn di chuột Force Touch'),
       (207,23,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (208,24,'Neural Engine 16 lõi'),
       (209,24,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (210,24,'Camera FaceTime HD 1080p'),
       (211,24,'Cổng sạc MagSafe 3'),
       (212,24,'Hai cổng Thunderbolt / USB 4'),
       (213,24,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (214,24,'Magic Keyboard với Touch ID'),
       (215,24,'Bàn di chuột Force Touch'),
       (216,24,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (217,25,'Neural Engine 16 lõi'),
       (218,25,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (219,25,'Camera FaceTime HD 1080p'),
       (220,25,'Cổng sạc MagSafe 3'),
       (221,25,'Hai cổng Thunderbolt / USB 4'),
       (222,25,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (223,25,'Magic Keyboard với Touch ID'),
       (224,25,'Bàn di chuột Force Touch'),
       (225,25,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (226,26,'Neural Engine 16 lõi'),
       (227,26,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (228,26,'Camera FaceTime HD 1080p'),
       (229,26,'Cổng sạc MagSafe 3'),
       (230,26,'Hai cổng Thunderbolt / USB 4'),
       (231,26,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (232,26,'Magic Keyboard với Touch ID'),
       (233,26,'Bàn di chuột Force Touch'),
       (234,26,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (235,27,'Neural Engine 16 lõi'),
       (236,27,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (237,27,'Camera FaceTime HD 1080p'),
       (238,27,'Cổng sạc MagSafe 3'),
       (239,27,'Hai cổng Thunderbolt / USB 4'),
       (240,27,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (241,27,'Magic Keyboard với Touch ID'),
       (242,27,'Bàn di chuột Force Touch'),
       (243,27,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (244,28,'Neural Engine 16 lõi'),
       (245,28,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (246,28,'Camera FaceTime HD 1080p'),
       (247,28,'Cổng sạc MagSafe 3'),
       (248,28,'Hai cổng Thunderbolt / USB 4'),
       (249,28,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (250,28,'Magic Keyboard với Touch ID'),
       (251,28,'Bàn di chuột Force Touch'),
       (252,28,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (253,29,'Neural Engine 16 lõi'),
       (254,29,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (255,29,'Camera FaceTime HD 1080p'),
       (256,29,'Cổng sạc MagSafe 3'),
       (257,29,'Hai cổng Thunderbolt / USB 4'),
       (258,29,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (259,29,'Magic Keyboard với Touch ID'),
       (260,29,'Bàn di chuột Force Touch'),
       (261,29,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (262,30,'Neural Engine 16 lõi'),
       (263,30,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (264,30,'Camera FaceTime HD 1080p'),
       (265,30,'Cổng sạc MagSafe 3'),
       (266,30,'Hai cổng Thunderbolt / USB 4'),
       (267,30,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (268,30,'Magic Keyboard với Touch ID'),
       (269,30,'Bàn di chuột Force Touch'),
       (270,30,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (271,31,'Neural Engine 16 lõi'),
       (272,31,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (273,31,'Camera FaceTime HD 1080p'),
       (274,31,'Cổng sạc MagSafe 3'),
       (275,31,'Hai cổng Thunderbolt / USB 4'),
       (276,31,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (277,31,'Magic Keyboard với Touch ID'),
       (278,31,'Bàn di chuột Force Touch'),
       (279,31,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (280,32,'Neural Engine 16 lõi'),
       (281,32,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (282,32,'Camera FaceTime HD 1080p'),
       (283,32,'Cổng sạc MagSafe 3'),
       (284,32,'Hai cổng Thunderbolt / USB 4'),
       (285,32,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (286,32,'Magic Keyboard với Touch ID'),
       (287,32,'Bàn di chuột Force Touch'),
       (288,32,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (289,33,'Màn hình Liquid Retina XDR 14 inch²'),
       (290,33,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (291,33,'Magic Keyboard với Touch ID'),
       (292,33,'Bàn di chuột Force Touch'),
       (293,33,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (294,34,'Màn hình Liquid Retina XDR 14 inch²'),
       (295,34,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (296,34,'Magic Keyboard với Touch ID'),
       (297,34,'Bàn di chuột Force Touch'),
       (298,34,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (299,35,'Màn hình Liquid Retina XDR 14 inch²'),
       (300,35,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (301,35,'Magic Keyboard với Touch ID'),
       (302,35,'Bàn di chuột Force Touch'),
       (303,35,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (304,36,'Màn hình Liquid Retina XDR 14 inch²'),
       (305,36,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (306,36,'Magic Keyboard với Touch ID'),
       (307,36,'Bàn di chuột Force Touch'),
       (308,36,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (309,37,'Màn hình Liquid Retina XDR 14 inch²'),
       (310,37,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (311,37,'Magic Keyboard với Touch ID'),
       (312,37,'Bàn di chuột Force Touch'),
       (313,37,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (314,38,'Màn hình Liquid Retina XDR 14 inch²'),
       (315,38,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (316,38,'Magic Keyboard với Touch ID'),
       (317,38,'Bàn di chuột Force Touch'),
       (318,38,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (319,39,'Màn hình Liquid Retina XDR 14 inch²'),
       (320,39,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (321,39,'Magic Keyboard với Touch ID'),
       (322,39,'Bàn di chuột Force Touch'),
       (323,39,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (324,40,'Màn hình Liquid Retina XDR 14 inch²'),
       (325,40,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (326,40,'Magic Keyboard với Touch ID'),
       (327,40,'Bàn di chuột Force Touch'),
       (328,40,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (329,41,'Màn hình Liquid Retina XDR 14 inch²'),
       (330,41,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (331,41,'Magic Keyboard với Touch ID'),
       (332,41,'Bàn di chuột Force Touch'),
       (333,41,'Bộ Tiếp Hợp Nguồn USB-C 96W'),
       (334,42,'Màn hình Liquid Retina XDR 14 inch²'),
       (335,42,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (336,42,'Magic Keyboard với Touch ID'),
       (337,42,'Bàn di chuột Force Touch'),
       (338,42,'Bộ Tiếp Hợp Nguồn USB-C 96W'),
       (339,43,'Màn hình Liquid Retina XDR 14 inch²'),
       (340,43,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (341,43,'Magic Keyboard với Touch ID'),
       (342,43,'Bàn di chuột Force Touch'),
       (343,43,'Bộ Tiếp Hợp Nguồn USB-C 96W'),
       (344,44,'Màn hình Liquid Retina XDR 14 inch²'),
       (345,44,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (346,44,'Magic Keyboard với Touch ID'),
       (347,44,'Bàn di chuột Force Touch'),
       (348,44,'Bộ Tiếp Hợp Nguồn USB-C 96W'),
       (349,45,'Màn hình Liquid Retina XDR 16 inch²'),
       (350,45,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (351,45,'Magic Keyboard với Touch ID'),
       (352,45,'Bàn di chuột Force Touch'),
       (353,45,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (354,46,'Màn hình Liquid Retina XDR 16 inch²'),
       (355,46,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (356,46,'Magic Keyboard với Touch ID'),
       (357,46,'Bàn di chuột Force Touch'),
       (358,46,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (359,47,'Màn hình Liquid Retina XDR 16 inch²'),
       (360,47,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (361,47,'Magic Keyboard với Touch ID'),
       (362,47,'Bàn di chuột Force Touch'),
       (363,47,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (364,48,'Màn hình Liquid Retina XDR 16 inch²'),
       (365,48,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (366,48,'Magic Keyboard với Touch ID'),
       (367,48,'Bàn di chuột Force Touch'),
       (368,48,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (369,49,'Màn hình Liquid Retina XDR 16 inch²'),
       (370,49,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (371,49,'Magic Keyboard với Touch ID'),
       (372,49,'Bàn di chuột Force Touch'),
       (373,49,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (374,50,'Màn hình Liquid Retina XDR 16 inch²'),
       (375,50,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (376,50,'Magic Keyboard với Touch ID'),
       (377,50,'Bàn di chuột Force Touch'),
       (378,50,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (379,51,'Màn hình Liquid Retina XDR 16 inch²'),
       (380,51,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (381,51,'Magic Keyboard với Touch ID'),
       (382,51,'Bàn di chuột Force Touch'),
       (383,51,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (384,52,'Màn hình Liquid Retina XDR 16 inch²'),
       (385,52,'Ba cổng Thunderbolt 4, cổng HDMI, khe thẻ nhớ SDXC, giắc cắm tai nghe, cổng MagSafe 3'),
       (386,52,'Magic Keyboard với Touch ID'),
       (387,52,'Bàn di chuột Force Touch'),
       (388,52,'Bộ Tiếp Hợp Nguồn USB-C 140W'),
       (389,53,'Neural Engine 16 lõi'),
       (390,53,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (391,53,'Camera FaceTime HD 1080p'),
       (392,53,'Cổng sạc MagSafe 3'),
       (393,53,'Hai cổng Thunderbolt / USB 4'),
       (394,53,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (395,53,'Magic Keyboard với Touch ID'),
       (396,53,'Bàn di chuột Force Touch'),
       (397,53,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (398,54,'Neural Engine 16 lõi'),
       (399,54,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (400,54,'Camera FaceTime HD 1080p'),
       (401,54,'Cổng sạc MagSafe 3'),
       (402,54,'Hai cổng Thunderbolt / USB 4'),
       (403,54,'Hỗ trợ một màn hình ngoài'),
       (404,54,'Magic Keyboard với Touch ID'),
       (405,54,'Bàn di chuột Force Touch'),
       (406,54,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (407,55,'Neural Engine 16 lõi'),
       (408,55,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (409,55,'Camera FaceTime HD 1080p'),
       (410,55,'Cổng sạc MagSafe 3'),
       (411,55,'Hai cổng Thunderbolt / USB 4'),
       (412,55,'Hỗ trợ một màn hình ngoài'),
       (413,55,'Magic Keyboard với Touch ID'),
       (414,55,'Bàn di chuột Force Touch'),
       (415,55,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (416,56,'Neural Engine 16 lõi'),
       (417,56,'Màn hình Liquid Retina 13,6 inch với True Tone²'),
       (418,56,'Camera FaceTime HD 1080p'),
       (419,56,'Cổng sạc MagSafe 3'),
       (420,56,'Hai cổng Thunderbolt / USB 4'),
       (421,56,'Hỗ trợ một màn hình ngoài'),
       (422,56,'Magic Keyboard với Touch ID'),
       (423,56,'Bàn di chuột Force Touch'),
       (424,56,'Bộ Tiếp Hợp Nguồn USB-C 30W'),
       (425,57,'Neural Engine 16 lõi'),
       (426,57,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (427,57,'Camera FaceTime HD 1080p'),
       (428,57,'Cổng sạc MagSafe 3'),
       (429,57,'Hai cổng Thunderbolt / USB 4'),
       (430,57,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (431,57,'Magic Keyboard với Touch ID'),
       (432,57,'Bàn di chuột Force Touch'),
       (433,57,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (434,58,'Neural Engine 16 lõi'),
       (435,58,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (436,58,'Camera FaceTime HD 1080p'),
       (437,58,'Cổng sạc MagSafe 3'),
       (438,58,'Hai cổng Thunderbolt / USB 4'),
       (439,58,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (440,58,'Magic Keyboard với Touch ID'),
       (441,58,'Bàn di chuột Force Touch'),
       (442,58,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (443,59,'Neural Engine 16 lõi'),
       (444,59,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (445,59,'Camera FaceTime HD 1080p'),
       (446,59,'Cổng sạc MagSafe 3'),
       (447,59,'Hai cổng Thunderbolt / USB 4'),
       (448,59,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (449,59,'Magic Keyboard với Touch ID'),
       (450,59,'Bàn di chuột Force Touch'),
       (451,59,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (452,60,'Neural Engine 16 lõi'),
       (453,60,'Màn hình Liquid Retina 15,3 inch với True Tone²'),
       (454,60,'Camera FaceTime HD 1080p'),
       (455,60,'Cổng sạc MagSafe 3'),
       (456,60,'Hai cổng Thunderbolt / USB 4'),
       (457,60,'Hỗ trợ lên đến hai màn hình ngoài (khi máy tính xách tay đang đóng nắp)'),
       (458,60,'Magic Keyboard với Touch ID'),
       (459,60,'Bàn di chuột Force Touch'),
       (460,60,'Bộ Tiếp Hợp Nguồn Cổng USB-C Kép 35W'),
       (461,61,'Màn hình Liquid Retina XDR 14 inch²'),
       (462,61,'Hai cổng Thunderbolt / USB 4, cổng HDMI, khe thẻ nhớ SDXC, jack cắm tai nghe, cổng MagSafe 3'),
       (463,61,'Magic Keyboard với Touch ID'),
       (464,61,'Bàn di chuột Force Touch'),
       (465,61,'Bộ Tiếp Hợp Nguồn USB-C 70W'),
       (466,62,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (467,62,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (468,62,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (469,62,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (470,62,'Kết nối và sạc với USB-C'),
       (471,64,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (472,64,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (473,64,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (474,64,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (475,64,'Kết nối và sạc với USB-C'),
       (476,67,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (477,67,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (478,67,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (479,67,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (480,67,'Kết nối và sạc với USB-C'),
       (481,68,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (482,68,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (483,68,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (484,68,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (485,68,'Kết nối và sạc với USB-C'),
       (486,69,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (487,69,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (488,69,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (489,69,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (490,69,'Kết nối và sạc với USB-C'),
       (491,70,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (492,70,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (493,70,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (494,70,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (495,70,'Kết nối và sạc với USB-C'),
       (496,71,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (497,71,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (498,71,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (499,71,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (500,71,'Kết nối và sạc với USB-C'),
       (501,72,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (502,72,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (503,72,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (504,72,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (505,72,'Kết nối và sạc với USB-C'),
       (506,73,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (507,73,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (508,73,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (509,73,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (510,73,'Kết nối và sạc với USB-C'),
       (511,74,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (512,74,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (513,74,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (514,74,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (515,74,'Kết nối và sạc với USB-C'),
       (516,75,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (517,75,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (518,75,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (519,75,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (520,75,'Kết nối và sạc với USB-C'),
       (521,76,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (522,76,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (523,76,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (524,76,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (525,76,'Kết nối và sạc với USB-C'),
       (526,77,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (527,77,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (528,77,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (529,77,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (530,77,'Kết nối và sạc với USB-C'),
       (531,78,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (532,78,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (533,78,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (534,78,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (535,78,'Kết nối và sạc với USB-C'),
       (536,79,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (537,79,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (538,79,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (539,79,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (540,79,'Kết nối và sạc với USB-C'),
       (541,80,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (542,80,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (543,80,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (544,80,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (545,80,'Kết nối và sạc với USB-C'),
       (546,81,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (547,81,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (548,81,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (549,81,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (550,81,'Kết nối và sạc với USB-C'),
       (551,82,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (552,82,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (553,82,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (554,82,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (555,82,'Kết nối và sạc với USB-C'),
       (556,83,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (557,83,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (558,83,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (559,83,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (560,83,'Kết nối và sạc với USB-C'),
       (561,84,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (562,84,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (563,84,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (564,84,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (565,84,'Kết nối và sạc với USB-C'),
       (566,85,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (567,85,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (568,85,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (569,85,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (570,85,'Kết nối và sạc với USB-C'),
       (571,86,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (572,86,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (573,86,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (574,86,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (575,86,'Kết nối và sạc với USB-C'),
       (576,87,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (577,87,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (578,87,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (579,87,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (580,87,'Kết nối và sạc với USB-C'),
       (581,88,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (582,88,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (583,88,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (584,88,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (585,88,'Kết nối và sạc với USB-C'),
       (586,89,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (587,89,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (588,89,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (589,89,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (590,89,'Kết nối và sạc với USB-C'),
       (591,90,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (592,90,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (593,90,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (594,90,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (595,90,'Kết nối và sạc với USB-C'),
       (596,91,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (597,91,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (598,91,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (599,91,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (600,91,'Kết nối và sạc với USB-C'),
       (601,92,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (602,92,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (603,92,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (604,92,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (605,92,'Kết nối và sạc với USB-C'),
       (606,93,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (607,93,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (608,93,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (609,93,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (610,93,'Kết nối và sạc với USB-C'),
       (611,94,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (612,94,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (613,94,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (614,94,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (615,94,'Kết nối và sạc với USB-C'),
       (616,95,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (617,95,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (618,95,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (619,95,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (620,95,'Kết nối và sạc với USB-C'),
       (621,96,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (622,96,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (623,96,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (624,96,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (625,96,'Kết nối và sạc với USB-C'),
       (626,97,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (627,97,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (628,97,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (629,97,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (630,97,'Kết nối và sạc với USB-C'),
       (631,98,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (632,98,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (633,98,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (634,98,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (635,98,'Kết nối và sạc với USB-C'),
       (636,99,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (637,99,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (638,99,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (639,99,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (640,99,'Kết nối và sạc với USB-C'),
       (641,100,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (642,100,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (643,100,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (644,100,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (645,100,'Kết nối và sạc với USB-C'),
       (646,101,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (647,101,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (648,101,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (649,101,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (650,101,'Kết nối và sạc với USB-C'),
       (651,102,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (652,102,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (653,102,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (654,102,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (655,102,'Kết nối và sạc với USB-C'),
       (656,103,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (657,103,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (658,103,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (659,103,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (660,103,'Kết nối và sạc với USB-C'),
       (661,104,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (662,104,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (663,104,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (664,104,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (665,104,'Kết nối và sạc với USB-C'),
       (666,105,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (667,105,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (668,105,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (669,105,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (670,105,'Kết nối và sạc với USB-C'),
       (671,106,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (672,106,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (673,106,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (674,106,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (675,106,'Kết nối và sạc với USB-C'),
       (676,107,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (677,107,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (678,107,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (679,107,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (680,107,'Kết nối và sạc với USB-C'),
       (681,108,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (682,108,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (683,108,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (684,108,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (685,108,'Kết nối và sạc với USB-C'),
       (686,109,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (687,109,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (688,109,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (689,109,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (690,109,'Kết nối và sạc với USB-C'),
       (691,110,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (692,110,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (693,110,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (694,110,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (695,110,'Kết nối và sạc với USB-C'),
       (696,111,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (697,111,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (698,111,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (699,111,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (700,111,'Kết nối và sạc với USB-C'),
       (701,112,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (702,112,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (703,112,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (704,112,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (705,112,'Kết nối và sạc với USB-C'),
       (706,113,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (707,113,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (708,113,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (709,113,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (710,113,'Kết nối và sạc với USB-C'),
       (711,114,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (712,114,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (713,114,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (714,114,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (715,114,'Kết nối và sạc với USB-C'),
       (716,115,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (717,115,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (718,115,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (719,115,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (720,115,'Kết nối và sạc với USB-C'),
       (721,116,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (722,116,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (723,116,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (724,116,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (725,116,'Kết nối và sạc với USB-C'),
       (726,117,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (727,117,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (728,117,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (729,117,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (730,117,'Kết nối và sạc với USB-C'),
       (731,118,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (732,118,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (733,118,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (734,118,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (735,118,'Kết nối và sạc với USB-C'),
       (736,119,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (737,119,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (738,119,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (739,119,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (740,119,'Kết nối và sạc với USB-C'),
       (741,120,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (742,120,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (743,120,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (744,120,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (745,120,'Kết nối và sạc với USB-C'),
       (746,121,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (747,121,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (748,121,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (749,121,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (750,121,'Kết nối và sạc với USB-C'),
       (751,122,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (752,122,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (753,122,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (754,122,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (755,122,'Kết nối và sạc với USB-C'),
       (756,123,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (757,123,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (758,123,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (759,123,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (760,123,'Kết nối và sạc với USB-C'),
       (761,124,'Thiết kế bằng nhôm và kính pha màu bền bỉ 15,5 cm với mặt trước có Ceramic Shield'),
       (762,124,'Dynamic Island hiển thị linh động các cảnh báo và Hoạt Động Trực Tiếp, nhờ đó bạn sẽ không bỏ lỡ thông tin khi đang làm việc khác'),
       (763,124,'Camera Chính 48MP với Telephoto 2x chụp rõ nét và tuyệt đẹp từng chi tiết cận cảnh hoặc từ xa'),
       (764,124,'Chip A16 Bionic hỗ trợ nhiếp ảnh điện toán, cho hiệu năng chơi game mượt mà và tiết kiệm pin tuyệt vời với pin dùng cả ngày'),
       (765,124,'Kết nối và sạc với USB-C');